service: pickmyplonk-app-api

# Use serverless-webpack plugin to transpile ES6/ES7
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: eu-west-2

functions:
  get_producers:
    handler: src/handlers/producer_handler.getProducers
    events:
      - http:
          path: producer
          method: get
          cors: true
          authorizer: aws_iam
  add_producer:
    handler: src/handlers/producer_handler.addProducer
    events:
      - http:
          path: producer
          method: post
          cors: true
          authorizer: aws_iam
  get_producer:
      handler: src/handlers/producer_handler.getProducer
      events:
        - http:
            path: producer/{id}
            method: get
            cors: true
            authorizer: aws_iam