service: pickmyplonk-app-api

# Use serverless-webpack plugin to transpile ES6/ES7
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: eu-west-2

functions:
  get_producers:
    handler: scripts/get_producers.main
    events:
      - http:
          path: producer
          method: get
          authorizer: aws_iam
