# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
defaults: &defaults
  working_directory: ~/pmp-backend-wdir
  docker:
    - image: node:8.9.1

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - run:
          name: Checking Versions
          command: |
             node --version
             npm --version
      - checkout
      # store the src files
      - save_cache:
          key: src-cache-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - .
      # restore dependencies
      - restore_cache:
          key: dependency-cache-{{ .Environment.CIRCLE_SHA1 }}
      # or install dependencies
      - run:
          name: Install npm
          command: npm install
      # and store them for later reuse
      - save_cache:
          key: dependency-cache-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ./node_modules
  deploy:
    <<: *defaults
    steps:
      - restore_cache:
          key: src-cache-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: dependency-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install AWS CLI
          working_directory: /
          command: |
            apt-get -y -qq update
            apt-get -y -qq install awscli
            aws configure set default.s3.signature_version s3v4
      - run:
          name: Install Serverless
          command: npm install -g serverless
      - run:
          name: Deploy via Serverless
          command: serverless deploy

workflows:
  version: 2
  build_and_deploy_api:
    jobs:
      - install
      - deploy:
          requires:
            - install